#!/bin/bash
set -e

SNAPSHOT_FILE="priv/llm_models/snapshot.json"
SNAPSHOT_OLD="/tmp/snapshot_old.json"
OUTPUT_FILE="/tmp/metadata_summary.md"

# Backup old snapshot for comparison
if [ -f "$SNAPSHOT_FILE" ]; then
  git show HEAD:"$SNAPSHOT_FILE" > "$SNAPSHOT_OLD" 2>/dev/null || echo "{}" > "$SNAPSHOT_OLD"
fi

echo "## Model Metadata Update" > "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "Automated metadata update from upstream sources." >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

if [ -f "$SNAPSHOT_FILE" ]; then
  PROVIDER_COUNT=$(jq '.providers | length' "$SNAPSHOT_FILE")
  MODEL_COUNT=$(jq '.models | length' "$SNAPSHOT_FILE")
  GENERATED_AT=$(jq -r '.metadata.generated_at' "$SNAPSHOT_FILE")
  
  echo "### Summary" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"
  echo "- Providers: $PROVIDER_COUNT" >> "$OUTPUT_FILE"
  echo "- Models: $MODEL_COUNT" >> "$OUTPUT_FILE"
  echo "- Generated: $GENERATED_AT" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"
  
  # Calculate changes
  if [ -f "$SNAPSHOT_OLD" ] && [ "$(cat "$SNAPSHOT_OLD")" != "{}" ]; then
    OLD_PROVIDER_COUNT=$(jq '.providers | length' "$SNAPSHOT_OLD" 2>/dev/null || echo "0")
    OLD_MODEL_COUNT=$(jq '.models | length' "$SNAPSHOT_OLD" 2>/dev/null || echo "0")
    
    PROVIDER_DIFF=$((PROVIDER_COUNT - OLD_PROVIDER_COUNT))
    MODEL_DIFF=$((MODEL_COUNT - OLD_MODEL_COUNT))
    
    if [ $PROVIDER_DIFF -ne 0 ] || [ $MODEL_DIFF -ne 0 ]; then
      echo "### Changes" >> "$OUTPUT_FILE"
      echo "" >> "$OUTPUT_FILE"
      
      if [ $PROVIDER_DIFF -gt 0 ]; then
        echo "- Providers added: $PROVIDER_DIFF" >> "$OUTPUT_FILE"
      elif [ $PROVIDER_DIFF -lt 0 ]; then
        echo "- Providers removed: ${PROVIDER_DIFF#-}" >> "$OUTPUT_FILE"
      fi
      
      if [ $MODEL_DIFF -gt 0 ]; then
        echo "- Models added: $MODEL_DIFF" >> "$OUTPUT_FILE"
      elif [ $MODEL_DIFF -lt 0 ]; then
        echo "- Models removed: ${MODEL_DIFF#-}" >> "$OUTPUT_FILE"
      fi
      
      echo "" >> "$OUTPUT_FILE"
    fi
  fi
fi

echo "### Changed Files" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "\`\`\`" >> "$OUTPUT_FILE"
git diff --stat priv/llm_models/upstream/ priv/llm_models/snapshot.json lib/llm_models/generated/valid_providers.ex >> "$OUTPUT_FILE"
echo "\`\`\`" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

echo "---" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "*Automatically generated by [build-metadata workflow](../.github/workflows/build-metadata.yml)*" >> "$OUTPUT_FILE"

echo "Summary generated at $OUTPUT_FILE"
cat "$OUTPUT_FILE"
